### ISSUE TITLE
Feature request: Support Bosch OTA

### ISSUE THREAD

**Issue by jclsn** [zigpy/zigpy#1279]
Bosch has released a new set of Zigbee devices last year and it would be great if the OTA updates for them were supported.

**Comment by puddly** [comment]
OTA via file upload has always been supported for devices without HTTP OTA providers.

In the future, OTA will be centralized and independent of individual OTA providers. Until this is implemented, file-based OTA is the way to go.

**Comment by Hedda** [comment]
@jclsn do you mean that you wish that zigpy should include an OTA provider for Bosch devices by default? If so then you must understand that for that to happen then Bosch first needs to provide unencrypted OTAU images and publish URLs publicly. See:

https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers

That is, the reason that zigpy already provide OTA providers for some manufacturers by default is a combination of the manufacturer already publishes OTAU images and OTA URLs publicly and a developer have added download code for it:

https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates

For reference see these other feature requests for OTA providers where the manufacturer already published OTA URLs publicly:

https://github.com/zigpy/zigpy/issues/992

https://github.com/zigpy/zigpy/issues/1060

https://github.com/zigpy/zigpy/issues/988

https://github.com/zigpy/zigpy/issues/1163

**Comment by jclsn** [comment]
@Hedda I am not sure. I just know that Z2M can already update the Bosch devices. I updated my TRV with its help now. 

@puddly No idea how file upload would work. I couldn't find a download portal for firmware updates for Bosch.

**Comment by Hedda** [comment]
> I just know that Z2M can already update the Bosch devices. I updated my TRV with its help now.

I don't believe Zigbee2MQTT users get Bosch Zigbee OTAU firmware images directly from URLs that Bosch publishes publicly. or? 

As far as I know, the OTA providers with "official" sources that Zigbee2MQTT has more than zigpy has are [Lixee](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/ota/lixee.ts) and [Ubisys](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/ota/ubisys.ts). See: 

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/src/lib/ota

The reason why zigbee-herdsman (library that Zigbee2MQTT depends on) provides OTA images from many other manufucturers than zigpy by default is that the Z2M community have just gone ahead to done the dirty work of collecting Zigbee OTA firmware images from various sources (such as example, Zigbee traffic sniffing and SoC firmware dumps) and then [cached, uploaded and shared those Zigbee OTAU images via an unofficial GitHub repository](https://github.com/Koenkk/zigbee-OTA) which then Zigbee2MQTT users then simply download their Zigbee OTAU images from (without most users knowing or caring where that OTA image actually got downloaded from). 

See this related feature request discussion here for more information about this indirect route method -> https://github.com/zigpy/zigpy/issues/535

(Bosch as example -> https://github.com/Koenkk/zigbee-OTA/tree/master/images/Bosch which Zigbee2MQTT's zigbee-herdsman library downloads indirectly via their unofficial zigbee-OTA repository on GitHub -> https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/lib/ota/zigbeeOTA.ts )

As such the Zigbee2MQTT implementation have in this chosen to interpret their usage as "[fair use](https://en.wikipedia.org/wiki/Fair_use)" and claim rights to do so even if manufacturer's copyrights and end-user license agreement might technically state something else. I am no lawer so no idea if they would win in court with that argument however personally I think that the worse thing that would probably happen is that they sooner of later get sent a cease and desist letter that request them to remove 

PS: Note that there are several benefits for manufacturers to publish their OTAs publicly that should motivate some of them.

For example, you can let companies and their marketing department know that they should be made aware of Home Assistant's "**_Works with Home Assistant_**" partner program with its matching "**_Works via Zigbee with Home Assistant_**" compatibility badges and ask them as a company if they would not consider joining that program, and by extension also provide Zigbee OTA images publicly to show that they approve of Home Assistant's ZHA integration as a supported Zigbee gateway implementation for their devices:

https://www.home-assistant.io/blog/2022/07/12/partner-program/

There it says "**_Works with Home Assistant partners are expected to provide firmware updates via user-friendly services provided by Home Assistant_**" under **_Responsibilities_** in a section there called "**_Provide easy firmware updates_**" which explains that "**_Works with Home Assistant partners are expected to provide firmware updates via user-friendly services provided by Home Assistant_**".

https://partner.home-assistant.io/

"_**There are manufacturers that are creating products that integrate into Home Assistant using standards like Z-Wave, Zigbee, or Matter (soon). In these cases, the integration is maintained by the Home Assistant community and Nabu Casa. These companies can still become a member of the Works with Home Assistant program but are relieved from integration maintenance.**_"

"_**With Home Assistant we are always working on educating our users about preferring local control and open standards when acquiring new products. This is also reflected in the “Works with Home Assistant” badges.**_"

![image](https://user-images.githubusercontent.com/6320001/196415473-f3020a0c-3a6d-407c-838f-4cf6cc5fa466.png)

FYI, see example ThirdReality, a Zigbee device making company that joined their partner program + having a zigpy OTA provider:

https://www.home-assistant.io/blog/2022/10/13/third-reality-partner/

PPS: This relates to zigpy as it may imply some commitment from companies to help with OTA updates and ZHA Device Handlers.

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers

https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling

https://github.com/zigpy/zha-device-handlers

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md

**Comment by jclsn** [comment]
Can't we make use of Z2M's OTA repo then? I mean they are already taking the risk, so we don't have to!

**Comment by Hedda** [comment]
> I couldn't find a download portal for firmware updates for Bosch.

@jclsn Please consider closing this issue if you do not have URLs for official Bosch URLs with public access to their OTA images.

> Can't we make use of Z2M's OTA repo then? I mean they are already taking the risk, so we don't have to!

I am sure most users would think that it would be very nice if some similar unofficial workarounds were natively built-in into Home Assistant’s built-in ZHA (Zigbee Home Automation) integration and the zigpy library/framework that it depends on, and technically it would not be difficult for developers to add an unofficial source (like an existing or a new GitHub repository with copies obtained via various unofficial means, none of which methods have legally been tested in a court of law but since the actual firmware images can only be used by owners of those devices to update the original devices there is probably a strong argument for “[fair use](https://en.wikipedia.org/wiki/Fair_use)”), but from project owners point-of-view there are many valid arguments why not include such unofficial sources, like for example; who the users should blame if the OTA upgrade image break/brick their device(?), and what if doing so in an unofficial way would get Nabu Casa and/or the Home Assistant project on bad side of companies that might someway otherwise want to partner with Nabu Casa and join the “Works with Home Assistant” program in the future → https://partner.home-assistant.io/ as easy firmware upgrades is part of the idea behind that partnership → https://www.home-assistant.io/blog/2022/07/12/partner-program/

“**_Responsibilities = "Provide easy firmware updates: Works with Home Assistant partners are expected to provide firmware updates via user-friendly services provided by Home Assistant_**”

FYI, the developers of Home Assistant's built-in Z-Wave integration which do have a matching GitHub repository with caches OTA images for Z-Wave devices have written this related statement into their [Z-Wave JS Firmware Update Service](https://github.com/zwave-js/firmware-updates) documentation addresses the question about providing firmware definition files from unofficial sources:

"***Warning: We will not accept firmware updates hosted by third parties. All updates must come from the respective device manufacturer. We make an exception for firmware that are publicly hosted by the manufacturer, but those may still require confirmation of the manufacturer's confirmation before merging.***"

Again, the best option for all would be if all device companies could be convinced to allow third parties to download official Zigbee OTA image files directly from official sources to be able to simply add download code to zigpy for enabling the ZHA integration to use them (regardless if they choose to partner with Nabu Casa for the "Works with Home Assistant" program or not) -> [https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers](https://github.com/zigpy/zigpy/wiki/OTA-Information-for-Manufacturers)

Again, refer to the related feature request discussion for more information about the mentioned indirect route method -> https://github.com/zigpy/zigpy/issues/535

If need help suggest that you instead start a separate informal discussion under -> https://github.com/zigpy/zigpy/discussions

Summery; you as an individual user can choose to add whatever unofficial source you want in you Home Assistant ZHA installation instance, that is already possible (check out, for example, the ZHA-Toolkit), but simply adding such an unofficial repository without vetting each and every OTA image could possibly have the consequence of ruining the reputation of zigpy/zha if a bad firmware brick users devices. That is at least one of the reasons why unofficial sources from a third-party are not considered, however, zigpy developers do mention there that they might consider creating their own Zigbee OTA firmware repository where they could properly vet and test flashing each firmware image to such a device before adding it, however maintaining such a repository would require a lot of work, so until then users just have to get by with pointing to their third-party repository of choice or adding firmware images manually (which of course is also already possible).

So if you are not a developer or have any contacts at the companies that manufacture the devices then maybe just check out the ZHA-Toolkit for adding downloading from unofficial resources like [Koenkk/zigbee-OTA](https://github.com/Koenkk/zigbee-OTA) and triggering firmware update using those -> https://github.com/mdeweerd/zha-toolkit/blob/main/README.md#ota_notify---downloadtrigger-device-fw-update

Regardless, all that is a different and separate request from getting Bosch OTA images directly from an official source published to the public by Bosch themselves, so suggest that you close this request unless you have URLs to such official sources.
