### ISSUE TITLE
Tuya 3 gang switch support is needed

### ISSUE THREAD

**Issue by loglux** [zigpy/zigpy#661]
https://www.aliexpress.com/item/1005001532044556.html
![image](https://user-images.githubusercontent.com/37578325/107776792-ef487a00-6d39-11eb-9c43-57e9f9ed3c96.png)
```
Device info
TS0043
by _TZ3000_bi6lpsew
Zigbee Coordinator
Zigbee info
IEEE: 84:71:27:ff:fe:13:bc:61
Nwk: 0x3e27
Device Type: EndDevice
LQI: 240
RSSI: -40
Last Seen: 2021-02-12T14:03:22
Power Source: Battery or Unknown
Quirk: zhaquirks.tuya.ts0043.BenexmartRemote0043

```

**Comment by loglux** [comment]
Any hope?

**Comment by Adminiuga** [comment]
It got the quirk, so must be doing zha_event then.

**Comment by loglux** [comment]
How can I help?

**Comment by Adminiuga** [comment]
keywords for google: home assistant, zha_event
This is a remote, does not have entities it does `zha_event` Check home assistant on how to listen to event to see what's being generated. zigbee channel on Home assistant discord channel is also a good place to start

Device got a quirk, so must be supported by `zha-device-handlers`. Zigpy is really wrong place for this kind of the issue.

**Comment by Hedda** [comment]
FYI, since part of the same organization on GitHub now members should be able to move issues between all the org repositories.

As such, developers that are members of the origination should be able to move issues from https://github.com/zigpy/zigpy/issues to https://github.com/zigpy/zha-device-handlers/issues and vice versa as needed, like when a uses post issues to the wrong repo.

That way if an issue can now be moved instead then there should no longer be any need for users to create a copy of an issue.
