### ISSUE TITLE
How to request integration

### ISSUE THREAD

**Issue by Aposei** [zigpy/zigpy#825]
Hi there.

I am a Jeedom user and when requesting the integration of a thermostatic radiator valve in the Zigbee plugin, I have been told that it must first be integrated in Zigpy. Can someone explain what I need to provide and where, to request the integration in Zigpy?

Thanks

**Comment by Aposei** [comment]
It is the RV05-ZigBee (_TZE200_hue3yfsn) model that is in the Tuya TRV matrix.

**Comment by Hedda** [comment]
@Aposei same as for https://github.com/zigpy/zigpy/issues/840

Does the [official Jeedom Zigbee Plugin](https://github.com/zigpy/zigpy/discussions/725) depend on zha-device-handlers / zha-quirks as an upstream dependency for quirk(s)?

https://github.com/zigpy/zha-device-handlers

https://pypi.org/project/zha-quirks/

If so then this issue perhaps belong in https://github.com/zigpy/zha-device-handlers/issues instead of here in zigpy issues?

**Comment by Hedda** [comment]
> I am a Jeedom user and when requesting the integration of a thermostatic radiator valve in the Zigbee plugin, I have been told that it must first be integrated in Zigpy. Can someone explain what I need to provide and where, to request the integration in Zigpy?

@Aposei similar to https://github.com/zigpy/zigpy/issues/840 wondering if this can be closed if it belongs in https://github.com/zigpy/zha-device-handlers/issues?

**Comment by Hedda** [comment]
@Aposei  Will you please consider closing this issue under the zigpy repository yourself?

Again high-level issues with device compatibility problems such as those you mention should be reported as issue to repository for "[ZHA Device Handlers](https://github.com/zigpy/zha-device-handlers)” (a.k.a. "[zha-quirks](https://pypi.org/project/zha-quirks)") instead of here in zigpy library repository which is only for low-level Zigbee issues:

https://github.com/zigpy/zha-device-handlers/issues

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md

If test now and still have problem then open an issue there -> https://github.com/zigpy/zha-device-handlers/issues/new/choose
